name: CI_Jefferson_Rodrigues

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Executando docker
        run: |
            docker run docker/whalesay cowsay Jefferson_Rodrigues
            echo "Imagem criada com sucesso!"

 
